### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by RisinT96** [MrSparc/idprom-repair#1]
Hello,

My father works at a factory that still uses SunBlade100/150 machines and some of his EEPROMs have gotten corrupted due to the battery running out, he managed to replace the batteries but he's having trouble reprogramming them.

He said that in OpenBoot 3.X there was an option to reprogram the eeproms (I guess it's what you've documented in the README), but since his machines are running OpenBoot 4.X he's unable to do that.

So my questions are:
1. Are you aware of any method that works on openboot 4.X?
2. What is the purpose of the provided kernel module?

It seems to randomize a MAC and serial no' and write it to the eeprom, every time the module is insmodded into the kernel.
But in order to do that you have to first be able to boot into linux, my dad claims that the machine refuses to start with a corrupted eeprom, is the procedure of using the module to first boot using a working chip, then hotswap to a faulty one and reprogram it using the kernel module?

Thank you very much for everything, and I'd be grateful if you could answer my questions.

Tal Risin.

PS. They are running UltraSPARC IIi or III if that makes any difference.

**Comment by MrSparc** [comment]
Hi Tal, 
Sorry for the delay to answer your question.
1) I have a Sun Blade 100 (OpenBoot 4.x Ultrasparc IIe) and his eeprom battery died, so I described the steps just as I did in README. You don't need the kernel module to do that, just Stop+A at boot to enter in the OpenBoot prompt and execute the commands. 
If the eeprom batteries have been replaced then you can use the described steps to reprogramming them. What is the errors your father are having when executes the commands in the README?

2) The kernel module is for who can't replace the battery and uses Linux, then can use a kernel module that randomize the MAC at boot time. 

I hope that this can help you.
