### ISSUE TITLE
Wrong offset value ?

### ISSUE THREAD

**Issue by Sch-LikA** [MrSparc/idprom-repair#2]
I tried following the doc for my own Sun Blade 100 (OpenBoot 4.0), I think your doc is wrong on part 8:

Offset
ok 1fd0 +

Shouldn't it be :

Offset
ok 1fd8 +

Btw thanks a lot for the info, I hope I'll get my Blade working !

**Comment by MrSparc** [comment]
Hi, yes you're right, according some notes on sun4c machines, the IDPROM starts at offset 0x7d8 from the start of the NVRAM. On sun4m, sun4d, and sun4u (like Sun Blade 100) machines the offset is 0x1fd8.
Fixed.
Thanks
